gem 'rack_hoptoad',       '>=0.0.3'
gem 'haml',               '~>2.2.0'
gem 'sinatra',            '~>0.9.4'
gem 'curb',               '>=0.3.7'
gem 'json',               '>=1.1.6'
gem 'oauth',              '=0.3.2'

gem 'do_sqlite3',         '>=0.9.12'
gem 'dm-validations',     '>=0.9.11'
gem 'dm-timestamps',      '>=0.9.11'


gem 'rake',                     :only => [:test]
gem 'rspec',                    :only => [:test]
gem 'rcov',                     :only => [:test]
gem 'bundler',      '>=0.5.0',  :only => [:test]
gem 'cucumber',                 :only => [:test]
gem 'webrat',       '~>0.5.0',  :only => [:test]
gem 'rack-test',    '~>0.4.2',  :only => [:test]
gem 'fakeweb',      '>=1.2.5',  :only => [:test]
gem 'ParseTree',    '>=3.0.4',  :only => [:test]
gem 'randexp',      '>=0.1.4',  :only => [:test]
gem 'dm-sweatshop', '>=0.9.11', :only => [:test]

disable_system_gems

# vim:ft=ruby
