source :gemcutter

group :runtime do
  gem 'rack_hoptoad',       '~>0.1.1', :require => 'rack/hoptoad'
  gem 'haml',               '~>2.2.0'
  gem 'sinatra',            '~>0.9.4'
  gem 'curb',               '>=0.3.7'
  gem 'json',               '>=1.1.6'
  gem 'oauth',              '=0.3.2'
  gem 'do_sqlite3',         '>=0.10.1.1'
  gem 'dm-core',            '~>0.10.2'
  gem 'dm-validations',     '~>0.10.2'
  gem 'dm-timestamps',      '~>0.10.2'
end

group :test do
  gem 'rake'
  gem 'rspec',                       :require => 'spec'
  gem 'rcov'
  gem 'shotgun'
  gem 'bundler',          '~>0.9.3'
  gem 'cucumber'
  gem 'webrat',           '~>0.7.0'
  gem 'rack-test',        '~>0.5.3', :require => 'rack/test'
  gem 'fakeweb',          '~>1.2.8'
  gem 'randexp',          '>=0.1.4'
  gem 'ParseTree',        '>=3.0.4', :require => [ ]
  #gem 'dm-sweatshop',     '~>0.10.2'
end

# vim:ft=ruby
