only :runtime do
  gem 'rack_hoptoad',        '~>0.1.1', :require_as => 'rack/hoptoad'
  gem 'haml',                '~>2.2.0'
  gem 'sinatra',             '~>0.9.4'
  #gem 'do_sqlite3',         '>=0.10.1.1'
  #gem 'dm-core',            '>=0.10.2'
  #gem 'dm-validations',     '>=0.10.2'
  #gem 'dm-timestamps',      '>=0.10.2'
end

only :development do
  gem 'shotgun'
end

only :test do
  gem 'rake'
  gem 'rspec',                       :require_as => 'spec'
  gem 'rcov'
  gem 'bundler',          '~>0.8.1'
  gem 'cucumber'
  gem 'webrat',           '~>0.7.0'
  gem 'rack-test',        '~>0.5.3', :require_as => 'rack/test'
  gem 'fakeweb',          '>=1.2.8'
  gem 'randexp',          '>=0.1.4'
  #gem 'ParseTree',        '>=3.0.4', :require_as => [ ]
  #gem 'dm-sweatshop',     '~>0.10.2'
end

disable_system_gems

# vim:ft=ruby
